config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root :to => 'home#index'
  get 'workspace' => 'workspace#index'
  get 'workspace/call_it_a_day' => 'workspace#call_it_a_day'
  get 'streak' => 'workspace#streak'
  get 'work_part_started' => 'workspace#work_part_started'
  get 'work_part_ended' => 'workspace#work_part_ended'
  get 'settings' => 'settings#index'
  patch 'settings' => 'settings#update'

  resources :tasks

end

app/models/my_config.rb
class MyConfig
  def rest_length
    5
  end

  def work_length
    25
  end
end

app/models/settings.rb
class Settings < RailsSettings::SettingObject
  validates_numericality_of :work_length
  validates_numericality_of :short_rest_length
  validates_numericality_of :long_rest_length

  def as_json(options=nil)
    { pomodoro:
      { work_length: work_length, short_rest_length: short_rest_length,
        long_rest_length: long_rest_length }
    }
  end
end

app/models/state.rb
class State
  delegate :tasks, to: :@user
  delegate :ai, :archive, :todo, to: :tasks

  def initialize user
    @user = user
  end

  def call_it_a_day!
    Task.transaction {
      move_undone_to_ai

      cloned_to_ai = clone_done_recurrent_to_ai
      move_done_to_archive
      cloned_to_ai.each &:save!

      @user.reset_streak
    }
  end

  private

  def clone_done_recurrent_to_ai
    todo.done.recurrent.map { |task|
      ai_task = task.dup
      ai_task.ai! save: false
      ai_task
    }
  end

  def move_done_to_archive
    todo.done.each &:archive!
  end

  def move_undone_to_ai
    todo.undone.each &:ai!
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  enum state: [:ai, :todo, :archive]

  scope :done, -> { where done: true }
  scope :undone, -> { where done: false }
  scope :recurrent, -> { where recurrent: true }

  validates_presence_of :description
  validates_uniqueness_of :description, scope: :user_id,
    conditions: -> { where.not(state: self.states[:archive]) },
    unless: proc { |r| r.archive? }

  validates_each :state do |record, attr, value|
    original_value = record.changed_attributes[attr]
    record.errors.add(attr, "can't be changed from :archive") \
      if original_value == 'archive'

    case value
      when 'ai' then validate_ai record, attr
      when 'todo' then validate_todo record, attr
      when 'archive' then validate_archive record, attr
    end
  end

  validates_each :recurrent do |record, attr, value|
    record.errors.add(attr, "can't have recurrent task in :archive") \
      if record.archive? && record.recurrent
  end
  validates :recurrent, :inclusion => {:in => [true, false]}

  validates_presence_of :length
  validates_numericality_of :length, only_integer: true,
    greater_than_or_equal_to: 1

  validates_numericality_of :spent, only_integer: true, min: 0
  validates_numericality_of :spent, greater_than_or_equal_to: 0,
    if: proc { |r| r.archive? }

  validates :done, :inclusion => {:in => [true, false]}

  def self.validate_ai record, attr
    record.errors.add(:spent, 'must be 0') unless record.spent.zero?
    record.errors.add(:done, 'must be false') unless record.done == false
  end

  def self.validate_archive record, attr
    record.errors.add(:done, 'must be true') unless record.done
  end

  def self.validate_todo record, attr
    record.errors.add(:spent, 'must be >= 0') unless record.spent >= 0
  end

  def ai! save: true
    self.attributes = { state: :ai, spent: 0, done: false }
    save! if save
  end

  def archive! save: true
    self.attributes = { state: :archive, done: true, recurrent: false }
    save! if save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :delete_all

  has_settings class_name: 'Settings' do |settings|
    settings.key :pomodoro,
      defaults: { work_length: 25, short_rest_length: 5, long_rest_length: 30 }
  end

  def work_part_started
    self.work_part_started_at = Time.current
    self.streak = 0 if long_gap?
  end

  def work_part_ended
    self.work_part_ended_at = Time.current
    self.streak += 1
  end

  def reset_streak
    update! streak: 0
  end

  def config
    @config ||= MyConfig.new
  end

  private

  def long_gap?
    return false unless work_part_started_at && work_part_ended_at

    work_part_started_at - work_part_ended_at > short_rest_length + rest_padding
  end

  def short_rest_length
    settings(:pomodoro).short_rest_length.to_f * 60
  end

  def rest_padding
    5.minutes
  end

  def work_length
    settings(:pomodoro).work_length.to_f * 60
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for resource
    stored_location_for(resource) || workspace_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def index
    @settings = current_user.settings :pomodoro

    respond_to do |format|
      format.json { render json: @settings }
      format.html
    end
  end

  def update
    @settings = current_user.settings :pomodoro

    if @settings.update_attributes settings_params
      flash[:success] = "Successfully saved settings"
      redirect_to workspace_path
    end
  end

  private

  def settings_params
    params.require(:settings)
      .permit(:work_length, :short_rest_length, :long_rest_length)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def create
    task = Task.new task_params
    task.user = current_user
    if task.save
      respond_with task
    else
      render json: { errors: task.errors.full_messages },
	status: :unprocessable_entity
    end
  end

  def destroy
    unless task = fetch_task
      render_no_such_task
    else
      task.destroy
      head :no_content
    end
  end

  def index
    unless %w(ai todo).include? params[:state]
      render nothing: true, status: :bad_request
      return
    end

    @tasks = current_user.tasks.order(:description).send(params[:state])
    respond_with @tasks
  end

  def update
    unless task = fetch_task
      render_no_such_task
      return
    end

    if task.update_attributes task_params
      respond_with
    else
      render json: { errors: task.errors.full_messages },
	status: :unprocessable_entity
    end
  end

  private

  def fetch_task
    current_user.tasks.find_by(id: params[:id])
  end

  def render_no_such_task
    render json: { errors: ['No such task'] }, status: :unprocessable_entity
  end

  def task_params
    params.require :task
    params[:task].permit(:description, :length, :recurrent, :spent, :done,
      :state)
  end
end

app/controllers/workspace_controller.rb
class WorkspaceController < ApplicationController
  respond_to :json

  before_action :authenticate_user!

  def index
  end

  def call_it_a_day
    State.new(current_user).call_it_a_day!
    redirect_to workspace_path
  end

  def streak
    respond_with current_user.streak
  end

  def work_part_started
    current_user.with_lock do
      current_user.work_part_started
      current_user.save!
    end

    respond_with current_user.streak
  end

  def work_part_ended
    current_user.with_lock do
      current_user.work_part_ended
      current_user.save!
    end

    respond_with current_user.streak
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_item_active_inactive_class(active_for_this_controller_name)
    controller_name == active_for_this_controller_name ?
      raw("class='active'") : ''

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/home/index.html.slim
.jumbotron
  h1 #{APP_NAME} welcomes you!
  p All your Pomodoro needs satisfied online.
  = link_to 'Sign up', new_user_registration_path,
    class: 'btn btn-primary btn-lg'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= APP_NAME %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if controller_name == "workspace" %>
    <meta name="turbolinks-cache-control" content="no-cache">
  <% end %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <% if Rails.env.test? %>
   <style type="text/css">
      .modal.fade, .fade {
	-webkit-transition: opacity 0.01s;
	-moz-transition: opacity 0.01s;
	-ms-transition: opacity 0.01s;
	-o-transition: opacity 0.01s;
	transition: opacity 0.01s;
      }
   </style>
  <%end%>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to APP_NAME, root_path, :class => 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
	<% if user_signed_in? %>
          <li <%= menu_item_active_inactive_class('workspace')  %>><%= link_to 'Workspace', workspace_path %></li>
          <li <%= menu_item_active_inactive_class('settings')  %>><%= link_to 'Settings', settings_path %></li>
	<% end %>
	<li>
          <a href="mailto:ledestin@gmail.com?subject=<%= APP_NAME %>">Contact</a>
	</li>
      </ul>

      <form class="navbar-right">
	<ul class="nav navbar-nav navbar-right">
	  <% if user_signed_in? %>
	    <li>
	      <p class="navbar-text"><%= current_user.email %></p>
	    </li>
	    <li>
	      <p class="navbar-btn">
		<%= link_to 'Sign out', destroy_user_session_path,
		  :class => 'btn btn-default', :method => :delete %>
	      </p>
	    </li>
	  <% else %>
	    <li>
	      <p class="navbar-btn">
		<%= link_to 'Sign up', new_user_registration_path,
		  :class => 'btn btn-default' %>
	      </p>
	    </li>
	    <li>
	      <p class="navbar-btn">
		<%= link_to 'Login', new_user_session_path,
		  :class => 'btn btn-default' %>
	      </p>
	    </li>
	  <% end %>
	</ul>

      </form>
    </div>
  </div>
</nav>

<% if flash[:success] %>
  <p class="alert alert-success"><%= flash[:success] %></p>
<% end %>
<% if notice %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert%>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container-fluid">
  <% unless controller.is_a? DeviseController %>
    <%= yield %>
  <% else %>
    <!-- Ensure Devise forms take less than full width of the page -->
    <div class="row">
      <div class="col-xs-8 col-lg-6">
	<%= yield %>
      </div>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/settings/index.html.slim
.row
  .col-xs-10.col-sm-6.col-md-5.col-lg-5
    = form_for @settings, url: settings_path, method: :patch do |f|
      .row
        .col
          = f.error_messages
      .row
        .col-xs-4.col-lg-4
          = label "work_length", "Work length"
        .col-xs-6.col-lg-6
          = f.number_field(:work_length, size: 3)
          |&nbsp;minutes
      .row
        .col-xs-4.col-lg-4
          = label "short_rest_length", "Short rest length"
        .col-xs-6.col-lg-6
          = f.number_field(:short_rest_length)
          |&nbsp;minutes
      .row
        .col-xs-4.col-lg-4
          = label "long_rest_length", "Long rest length"
        .col-xs-6.col-lg-6
          = f.number_field(:long_rest_length)
          |&nbsp;minutes
      .row
        .col-xs-6.col-lg-6
          = f.submit "Save", class: "btn btn-large btn-success"

app/views/settings/update.html.slim
index.html.slim

app/views/workspace/index.html.slim
#timerModal.modal.fade data-backdrop='static'
  .modal-dialog
    .modal-content
      .modal-header
        h2.modal-title id='timerTitle'
      .modal-body
        = audio_tag 'msonarsub.mp3', loop: true, id: 'timerAudio'
        .row
          .col-xs-4.col-xs-offset-4
            #timer
        br
        .row
          .col-xs-12
            .well
              h4 Add a remembered activity to AI
              #timerAddForm
      .modal-footer
        button[type='button' class='btn btn-lg btn-success'
          id='timerLongRestButton' onClick='Oxheart.Workspace.startLongRest()']
          | Start LONG rest
        button[type='button' class='btn btn-lg btn-success'
          id='timerRestButton' onClick='Oxheart.Workspace.startRest()']
          | Start SHORT rest
        button[type='button' class='btn btn-lg btn-success'
          id='timerReturnButton'
          onClick='Oxheart.Workspace.returnToWorkspace()']
          | Return to workspace
        button[type='button' class='btn btn-danger btn-lg'
          id='timerCancelButton'
          onClick='Oxheart.Workspace.cancelPomodoro()'] Cancel pomodoro

#root